//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniWorkforce.Config {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class UniWorkforce : global::System.Configuration.ApplicationSettingsBase {
        
        private static UniWorkforce defaultInstance = ((UniWorkforce)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UniWorkforce())));
        
        public static UniWorkforce Default {
            get {
                return defaultInstance;
            }
        }
    }
}
