//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Shared.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugins.Shared.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ActivitiesEnglishMap {
            get {
                object obj = ResourceManager.GetObject("ActivitiesEnglishMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] AvailableActivities {
            get {
                object obj = ResourceManager.GetObject("AvailableActivities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--该配置文件保存默认包源，请勿手动修改--&gt;
        ///&lt;configuration&gt;
        ///  &lt;packageSources&gt;
        ///    &lt;!-- Nuget默认包源地址--&gt;
        ///    &lt;!--&lt;add key=&quot;本地（内置包仅供测试）&quot; value=&quot;Packages&quot; /&gt;--&gt;
        ///  &lt;/packageSources&gt;
        ///  &lt;config&gt;
        ///    &lt;!-- 指定全局包下载路径 --&gt;
        ///    &lt;add key=&quot;globalPackagesFolder&quot; value=&quot;%LocalAppData%\UniStudio\Packages\.nuget\packages&quot; /&gt;
        ///  &lt;/config&gt;
        ///&lt;/configuration&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string NuGet_Default {
            get {
                return ResourceManager.GetString("NuGet_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--该配置文件保存用户自定义包源，请在包管理器中进行操作来更新该文件信息--&gt;
        ///&lt;configuration&gt;
        ///  &lt;packageSources&gt;
        ///    &lt;!-- Nuget用户自定义包源地址 --&gt;
        ///    &lt;add key=&quot;nuget.org&quot; value=&quot;https://api.nuget.org/v3/index.json&quot; /&gt;
        ///  &lt;/packageSources&gt;
        ///&lt;/configuration&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string NuGet_User {
            get {
                return ResourceManager.GetString("NuGet_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Python_Mode {
            get {
                object obj = ResourceManager.GetObject("Python_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
